---@class MySettings
local settings = {
  icons = {
    diagnostics = {
      -- Error = " ",
      Warn = " ",
      -- Hint = " ",
      Info = " ",
      BoldError = "",
      Error = "",
      BoldWarning = "",
      Warning = "",
      BoldInformation = "",
      Information = "",
      BoldQuestion = "",
      Question = "",
      BoldHint = "",
      Hint = "󰌶",
      Debug = "",
      Trace = "✎",
      -- Error = " ",
      -- Warn = " ",
      -- Hint = " ",
      -- Info = " ",
    },
    git = {
      added = " ",
      modified = " ",
      removed = " ",
      -- added = " ",
      -- modified = " ",
      -- removed = " ",
    },
    kinds = {
      Array = " ",
      Boolean = " ",
      Class = " ",
      Color = " ",
      Constant = " ",
      Constructor = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Folder = " ",
      Function = " ",
      Interface = " ",
      Key = " ",
      Keyword = " ",
      Method = " ",
      Module = " ",
      Namespace = " ",
      Null = "ﳠ ",
      Number = " ",
      Object = " ",
      Operator = " ",
      Package = " ",
      Property = " ",
      Reference = " ",
      Snippet = " ",
      String = " ",
      Struct = " ",
      Text = " ",
      TypeParameter = " ",
      Unit = " ",
      Value = " ",
      Variable = " ",
    },
    ui = {
      Target = "󰀘",
    }
  },
}

return settings
