return {
  ['Explain architecture'] = require('plugins.ai.codecompanion.promptlibrary.explain_architecture'),
  ['Suggest Refactoring'] = require('plugins.ai.codecompanion.promptlibrary.suggest_refactoring'),
  ['Add DocBlock'] = require('plugins.ai.codecompanion.promptlibrary.docblock'),
  ['Git Diff Code Review'] = require('plugins.ai.codecompanion.promptlibrary.git_diff_code_review'),
  ['inline'] = require('plugins.ai.codecompanion.promptlibrary.inline'),
  ['Code review'] = require('plugins.ai.codecompanion.promptlibrary.code_review'),
  ['Explain code'] = require('plugins.ai.codecompanion.promptlibrary.explain_code'),
  ['Code Expert'] = require('plugins.ai.codecompanion.promptlibrary.code_expert'),
  ['Review'] = require('plugins.ai.codecompanion.promptlibrary.review'),
  ['Generate Docstring'] = require('plugins.ai.codecompanion.promptlibrary.doc_string'),
  ['Refactor'] = require('plugins.ai.codecompanion.promptlibrary.refactor'),
  ['Pull Request'] = require('plugins.ai.codecompanion.promptlibrary.pullrequest'),
  ['Spell'] = require('plugins.ai.codecompanion.promptlibrary.spell'),
  ['Bug Finder'] = require('plugins.ai.codecompanion.promptlibrary.bug_finder'),
  ['Agent Mode'] = require('plugins.ai.codecompanion.promptlibrary.agent_mode'),
}
