return {
  'm4xshen/hardtime.nvim',
  event = 'VeryLazy',
  dependencies = { 'MunifTanjim/nui.nvim', 'nvim-lua/plenary.nvim' },
  keys = {
    { '<leader>hd', '<cmd>Hardtime disable<cr>', desc = 'HardTime Disable' },
    { '<leader>he', '<cmd>Hardtime enable<cr>', desc = 'HardTime Enable' },
  },
  opts = {
    allow_different_key = true,
    disabled_filetypes = {
      'Diffview*',
      'Dressing*',
      'Neogit*',
      'NvimTree',
      'ToggleTerm',
      'alpha',
      'checkhealth',
      'help',
      'httpResult',
      'lazy',
      'lazygit',
      'lspinfo',
      'mason',
      'markdown',
      'codecompanion',
      'guihua',
      'neotest-summary',
      'netrw',
      'netrw',
      'noice',
      'notify',
      'oil',
      'prompt',
      'qf',
      'undotree',
      'trouble',
      'Outline',
      'dapui_scopes',
      'dapui_stacks',
      'dapui_console',
      'dapui-repl',
      'dapui_watches',
      'dapui_breakpoints',
      'dapui*',
    },
    hints = {
      ['[dcyvV][ia]%('] = {
        message = function(keys)
          return 'Use ' .. keys:sub(1, 2) .. 'b instead of ' .. keys
        end,
        length = 3,
      },
    },
  },
}
