return {
  {
    'folke/which-key.nvim',
    event = 'VeryLazy',
    opts = {
      defaults = {},
      timeoutlen = 500,
      delay = 500,
      disable = {
        bt = {},
        ft = { 'TelescopePrompt' },
      },
      preset = 'modern',
      spec = {
        mode = { 'n', 'v' },
        { '<leader>b', group = '+[buffer]' },
        { '<leader>c', group = '+[code]' },
        { '<leader>d', group = '+[debug]' },
        { '<leader>f', group = '+[file/find]' },
        { '<leader>g', group = '+[git]' },
        { '<leader>gd', group = 'diffview' },
        -- { '<leader>a', group = '+[codecompanion]' },
        { '<leader>a', group = '+[ai]', icon = '󰚩' },
        { '<leader>h', group = 'hardtime' },
        { '<leader>n', group = 'noice' },
        { '<leader>o', group = '+[overseer]' },
        { '<leader>q', group = '+[quit/session]' },
        { '<leader>s', group = 'search' },
        { '<leader>t', group = '+[test]' },
        { '<leader>u', group = '+[ui]' },
        { '<leader>w', group = '+[windows]' },
        { '<leader>l', group = '+[utils]' },
        { '<leader>x', group = '+[diagnostics/quickfix]', icon = { icon = '󱖫 ', color = 'green' } },
        { 'z', group = 'fold' },
        { '[', group = 'prev' },
        { ']', group = 'next' },
      },
    },
  },
}
